name: Longburn Adventist College
favicon: null
layout_spectrum: 0.357
typography_spectrum: 0.88501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e51a4'
    - '#ffffff'
    - '#f7a81b'
    - '#d1d8ed'
    - '#7988c3'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
