name: Longburn Adventist College
favicon: null
layout_spectrum: 0.6687139612622559
typography_spectrum: 0.4346120140980929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e51a4'
    - '#ffffff'
    - '#f7a81b'
    - '#d1d8ed'
    - '#7988c3'
  brandStrength: 0.8125
  lightness: 0.30251488485373557
  saturation: 0.03970015677623451
  rhythmicContrast: 0.8869956585112959
purpose: []
